# Generated by Django 5.1.2 on 2024-10-19 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_faculty_profile_ort_score_group_lesson_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_enrollment_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(default='default_code', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='duration_years',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Длительность обучения (лет)'),
        ),
        migrations.AddField(
            model_name='group',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_groups', to='main.faculty'),
        ),
        migrations.CreateModel(
            name='GroupStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_ort_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('duration_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Длительность обучения (лет)')),
                ('all_students', models.IntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.faculty')),
            ],
        ),
    ]
