# Generated by Django 5.1.2 on 2024-10-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faculty_is_enrollment_open_group_code_group_curator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupstudents',
            options={'verbose_name': 'Группа(временная)', 'verbose_name_plural': 'Группы(временные)'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='studentdata',
            options={'verbose_name': 'Информации студента(связанные с универиситетом)', 'verbose_name_plural': 'Информации студентов(связанные с универиситетом)'},
        ),
    ]
