# Generated by Django 5.1.2 on 2024-10-22 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_faculty_options_alter_group_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student_count',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='groups', to='main.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='groups_students',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='main.groupstudents'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studen_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
