# Generated by Django 5.1.2 on 2024-10-26 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_group_student_count_remove_lesson_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='groups_students',
            new_name='group_students',
        ),
        migrations.AddField(
            model_name='group',
            name='contract',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер контракта'),
        ),
        migrations.AddField(
            model_name='groupstudents',
            name='contract',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер контракта'),
        ),
        migrations.AlterField(
            model_name='group',
            name='curator',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
