# Generated by Django 5.1.2 on 2024-10-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_groups_students_lesson_group_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='temporary_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_data', to='main.groupstudents'),
        ),
    ]
