# Generated by Django 5.1.2 on 2024-11-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_name_profile_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_district',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
