# Generated by Django 5.1.2 on 2024-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(null=True, upload_to='faculty/photo'),
        ),
    ]
