# Generated by Django 5.1.2 on 2024-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_faculty_description_faculty_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudents',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='groupstudents',
            name='photo',
            field=models.ImageField(null=True, upload_to='group/photo'),
        ),
    ]
