# Generated by Django 5.1.2 on 2024-11-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_groupstudents_description_groupstudents_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
