# Generated by Django 5.1.2 on 2024-11-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_lesson_details_groupstudents_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstudents',
            name='description',
        ),
    ]
