# Generated by Django 5.1.2 on 2024-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_lesson_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdata',
            options={'verbose_name': 'Информация студента(связанные с универиситетом)', 'verbose_name_plural': 'Информации студентов(связанные с универиситетом)'},
        ),
        migrations.AddField(
            model_name='studentdata',
            name='form_of_training',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
