# Generated by Django 5.1.2 on 2024-11-21 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_studentdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudents',
            name='budget_place',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
