# Generated by Django 5.1.2 on 2024-11-23 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_groupstudents_budget_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupstudents',
            old_name='budget_place',
            new_name='budget_place_percent',
        ),
        migrations.CreateModel(
            name='BudgetApplicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_wont_to_budget', models.BooleanField(default=False)),
                ('temporary_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_applicants', to='main.groupstudents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_applicants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хочет ли абитуриент вступить в эту группу',
                'verbose_name_plural': 'Хотят ли абитуриенты вступить в эту группу',
            },
        ),
    ]
