# Generated by Django 5.1.2 on 2024-11-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_budget_place_groupstudents_budget_place_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetapplicants',
            name='temporary_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_applicants', to='main.groupstudents'),
        ),
    ]
