# Generated by Django 5.1.2 on 2024-11-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_budgetapplicants_temporary_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstudents',
            name='all_students',
        ),
    ]
